// Name: Rahim
// Surname: Rzayev
/* Description: A calculator has been provided with arithmetic operations such as Addition, Subtraction, Multiplication, and Division. 
The calculator includes a backspace button that deletes the last character in the TextField. 
Users can observe the entire calculation process on the TextField.*/
package jCalculator;

/**
 *
 * @author rahim
 */
public class JavaCalculator extends javax.swing.JFrame {

    /**
     * Creates new form JavaCalculator
     */
    
    private boolean decdisp;  //field named initialized , and its use in a method named synchronizeConnection .
    String  value; /* String method is used to declare a variable and this variable is value */
    double fnum;   //num variable is declared  
    double snum; //fnum variable is declared
    String operator; /* String method is used to declare a variable and this variable is operator */
    double ans;  //ans variable is declared
   
    public JavaCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnDevide = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        txtdisplay = new javax.swing.JTextField();
        btnPlus = new javax.swing.JButton();
        btnTimes = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setPreferredSize(new java.awt.Dimension(310, 440));

        jPanel1.setPreferredSize(new java.awt.Dimension(360, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn0.setBackground(new java.awt.Color(51, 255, 51));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn0.setPreferredSize(new java.awt.Dimension(70, 50));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 50, 50));

        btnEqual.setBackground(new java.awt.Color(51, 255, 51));
        btnEqual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEqual.setText("=");
        btnEqual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEqual.setPreferredSize(new java.awt.Dimension(70, 50));
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        jPanel1.add(btnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 50, 50));

        btnBack.setBackground(new java.awt.Color(51, 255, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("←");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setPreferredSize(new java.awt.Dimension(70, 50));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, 50));

        btn9.setBackground(new java.awt.Color(51, 255, 51));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn9.setPreferredSize(new java.awt.Dimension(70, 50));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 50, 50));

        btn8.setBackground(new java.awt.Color(51, 255, 51));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8.setPreferredSize(new java.awt.Dimension(70, 50));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 50, 50));

        btnMinus.setBackground(new java.awt.Color(51, 255, 51));
        btnMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMinus.setText("-");
        btnMinus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMinus.setPreferredSize(new java.awt.Dimension(70, 50));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 50, 50));

        btn6.setBackground(new java.awt.Color(51, 255, 51));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6.setPreferredSize(new java.awt.Dimension(70, 50));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 50, 50));

        btn5.setBackground(new java.awt.Color(51, 255, 51));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.setPreferredSize(new java.awt.Dimension(70, 50));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 50, 50));

        btn7.setBackground(new java.awt.Color(51, 255, 51));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn7.setPreferredSize(new java.awt.Dimension(70, 50));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 50, 50));

        btn4.setBackground(new java.awt.Color(51, 255, 51));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.setPreferredSize(new java.awt.Dimension(70, 50));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, 50));

        btn1.setBackground(new java.awt.Color(51, 255, 51));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.setPreferredSize(new java.awt.Dimension(70, 50));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 50));

        btnPoint.setBackground(new java.awt.Color(51, 255, 51));
        btnPoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPoint.setText(".");
        btnPoint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPoint.setPreferredSize(new java.awt.Dimension(70, 50));
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });
        jPanel1.add(btnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 50, 50));

        btn3.setBackground(new java.awt.Color(51, 255, 51));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.setPreferredSize(new java.awt.Dimension(70, 50));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 50, 50));

        btnDevide.setBackground(new java.awt.Color(51, 255, 51));
        btnDevide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDevide.setText("/");
        btnDevide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDevide.setPreferredSize(new java.awt.Dimension(70, 50));
        btnDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevideActionPerformed(evt);
            }
        });
        jPanel1.add(btnDevide, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 50, 50));

        btn2.setBackground(new java.awt.Color(51, 255, 51));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.setPreferredSize(new java.awt.Dimension(70, 50));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 50, 50));

        txtdisplay.setBackground(new java.awt.Color(204, 204, 204));
        txtdisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdisplay.setForeground(new java.awt.Color(102, 0, 204));
        txtdisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtdisplay.setSelectionColor(new java.awt.Color(51, 51, 255));
        txtdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdisplayActionPerformed(evt);
            }
        });
        jPanel1.add(txtdisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 50));

        btnPlus.setBackground(new java.awt.Color(51, 255, 51));
        btnPlus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPlus.setText("+");
        btnPlus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlus.setPreferredSize(new java.awt.Dimension(70, 50));
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, 50));

        btnTimes.setBackground(new java.awt.Color(51, 255, 51));
        btnTimes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTimes.setText("*");
        btnTimes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTimes.setPreferredSize(new java.awt.Dimension(70, 50));
        btnTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimesActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 50, 50));

        btnClear1.setBackground(new java.awt.Color(51, 255, 51));
        btnClear1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear1.setText("C");
        btnClear1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear1.setPreferredSize(new java.awt.Dimension(70, 50));
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
    /* These codes are for displaying number 9 on the txtDisplay textField when the user hits the "9" button.*/
       value= txtdisplay.getText()+"9"; /*The innerText "9" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
    /* These codes are for displaying number 1 on the txtDisplay textField when the user hits the "1" button.*/  
       value= txtdisplay.getText()+"1"; /*The innerText "1" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
    /* These codes are for displaying number 2 on the txtDisplay textField when the user hits the "2" button.*/
       value= txtdisplay.getText()+"2"; /*The innerText "2" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
    /* These codes are for displaying number 3 on the txtDisplay textField when the user hits the "3" button.*/
       value= txtdisplay.getText()+"3"; /*The innerText "3" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
    /* These codes are for displaying number 4 on the txtDisplay textField when the user hits the "4" button.*/
        value= txtdisplay.getText()+"4"; /*The innerText "4" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
    /* These codes are for displaying number 5 on the txtDisplay textField when the user hits the "5" button.*/
       value= txtdisplay.getText()+"5"; /*The innerText "5" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
    /* These codes are for displaying number 6 on the txtDisplay textField when the user hits the "6" button.*/
       value= txtdisplay.getText()+"6"; /*The innerText "6" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
    /* These codes are for displaying number 7 on the txtDisplay textField when the user hits the "7" button.*/
       value= txtdisplay.getText()+"7"; /*The innerText "7" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
    /* These codes are for displaying number 8 on the txtDisplay textField when the user hits the "8" button.*/
       value= txtdisplay.getText()+"8"; /*The innerText "8" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
           if(! decdisp){ //he Java if statement is the most simple decision-making statement. It is used to decide whether a certain statement or block of statements will be executed or not
        txtdisplay.setText(txtdisplay.getText()+"."); //this code is in TextField "." shows.
     }
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevideActionPerformed
      /* There are codes for displaying numbers on a txt file. When the user clicks the "/" button, the textField will be displayed.*/
       value= txtdisplay.getText()+" / "; /*The innerText "/" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btnDevideActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
       /* There are codes for displaying numbers on a txt file. When the user clicks the "-" button, the textField will be displayed.*/
       value= txtdisplay.getText()+" - "; /*The innerText "-" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
        
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         if(txtdisplay.getText().length()>0) // This if statement are used to create the condition
        {
            
            StringBuilder s=new StringBuilder(txtdisplay.getText());//This code is written for getting text
            
            s.deleteCharAt(txtdisplay.getText().length()-1);//This code is written deleting data for one space on the textfield 
            
            txtdisplay.setText(s.toString());//This code is written deleting data for one space on the textfield 
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
    /* These codes are for displaying number 0 on the txtDisplay textField when the user hits the "0" button.*/
        value= txtdisplay.getText()+"0"; /*The innerText "0" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // This code generates the equal function.
        
        //variable is declared
        int x=txtdisplay.getText().length(); //The innerText is returned by the getText( ) method. These are the codes for retrieving text from txtdisplay. 
        
        fnum= Double.parseDouble(value.substring(0, value.indexOf(" "))); //The indexOf() function returns the location in a string of the first occurrence of the provided character(s).
        snum= Double.parseDouble(value.substring(value.indexOf(" ")+2, x)); //The indexOf() function returns the location in a string of the first occurrence of the provided character(s).
        String operator= value.substring(value.indexOf(" ")+1,value.indexOf(" ")+2); //The indexOf() function returns the location in a string of the first occurrence of the provided character(s).
        
        if(operator.equals("+")) // these codes are for addition
        {   
            ans=fnum + snum;
        }
        if(operator.equals("-")) //these codes are for subtracting
        {   
            ans=fnum - snum;
        }
        if(operator.equals("*")) // these codes are for multiplication
        {   
            ans=fnum * snum;
        }
        if(operator.equals("/")) //these codes are for division
        {   
            ans=fnum / snum;
        }
        
        txtdisplay.setText(value + "=" + String.valueOf(ans)); // The setText() method is used to set the Value string and "=", and the result (complete computation) is displayed in the txtdisplay TextField.
    }//GEN-LAST:event_btnEqualActionPerformed

    private void txtdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdisplayActionPerformed
    // these codes are for demonstrating calculation on the screen
    }//GEN-LAST:event_txtdisplayActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
       /* There are codes for displaying numbers on a txt file. When the user clicks the "+" button, the textField will be displayed.*/
       value= txtdisplay.getText()+" + "; /*The innerText "+" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimesActionPerformed
       /* There are codes for displaying numbers on a txt file. When the user clicks the "*" button, the textField will be displayed.*/
       value= txtdisplay.getText()+" * "; /*The innerText "*" is returned by the getText( ) method. This value string is the same as this.*/
       txtdisplay.setText(value); /*To set the Value string, use the setText() function.*/
    }//GEN-LAST:event_btnTimesActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        txtdisplay.setText("");   // This code generates the clear function.
    }//GEN-LAST:event_btnClear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JavaCalculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDevide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnTimes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtdisplay;
    // End of variables declaration//GEN-END:variables
}
